server:
  port: 8999
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
#zuul:
#  routes:
#    service-gateway:
#      serviceId: STUDENTSERVICE
#    service-gateway2:
#      serviceId: MICROSERVICE
