server:
  port: 8095
spring:
  application:
    name: orderservice
  profiles:
    active: default
  cloud:
    config:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: P@ssw0rd
    initialization-mode: always
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/