server:
  port: 8093
spring:
  application:
    name: productservice
  profiles:
    active: default
  cloud:
    config:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: P@ssw0rd
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka