server:
  port: 8098
spring:
  application:
    name: productlistservice
  profiles:
    active: default
  cloud:
    config:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/productlist
    username: root
    password: P@ssw0rd
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka