spring:
  application:
    name: orderservice
  profiles:
    active: default
  cloud:
    config:
      enabled: true
server:
  port: 8093
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/